### ISSUE TITLE
MismatchedInputException: Cannot deserialize instance of `int` out of START_OBJECT token

### ISSUE THREAD

**Issue by blackdigger1337** [FasterXML/jackson-dataformat-xml#416]
Hello!
I'm trying to parse xml like
```
<channel>
    <id type="integer">42</id>
    <node_id nil="true"/>
    ...
    <name>name</name>
    <service_name nil="true"/>
</channel>
```
into Kotlin object
```
data class Channel(
  val id: Int,
  val nodeId: Int? = null,
  val name: String,
  val serviceName: String? = null
)
```
and get
```MismatchedInputException: Cannot deserialize instance of `int` out of START_OBJECT token```
version: jackson-dataformat-xml:2.11.0

As I understand, it happens because of "type" attribute which makes jackson think its an object and not primitive.
I've been fighting this XML deserialization problem for a couple of days already and can't find a solution.
I have no control over XML format which I receive, unfortunately.

Here is test app which reproduces the issue - https://gist.github.com/blackdigger1337/1bee83d70d313603cd60d0b882703535

How to fix this issue?
Probably I can declare a wrapper class which would help me to parse this xml, as is suggested here https://stackoverflow.com/questions/28213396/jackson-xml-how-can-i-ignore-an-xml-attribute, but depending on the state of channel I need to be able to parse the same field as int if 1) it has no "type" attribute and has only tag value 2) it has null value but has ugly "nil" attribute 3) it is non-null int but has "type" attribute.
Same with string field.
But wrapper classes are really ugly because there will be many fields like that and anyway I couldn't make it work.
I guess it would be enough to ignore attributes somehow as a workaround, I don't need them.

Also I will further need to serialize this object back to XML, so more head ache with wrappers and annotations...

PS: this question was also asked here https://gitter.im/FasterXML/jackson-databind?at=5efe2079bb149531ede5a408 and got no reply yet.

**Comment by cowtowncoder** [comment]
I think the answer is "is fixed in 2.12 branch, will work in 2.12.0"; you may be able to verify this by using 2.12.0-SNAPSHOT from Sonatype OSS Maven repo (or building locally).
There is probably no practical way to configure this to work with 2.11 or earlier versions unfortunately: the issue is that existence of attribute(s) will make content be seen as "Object value" instead of scalar (text). 2.12 adds specific handling for this, but changes on dataformat module and databind are too big to be backported to 2.11.

**Comment by blackdigger1337** [comment]
Thanks a lot for such quick fix!
I've tested on 2.12.0-SNAPSHOT and it seems to be ok.

**Comment by cowtowncoder** [comment]
@blackdigger1337 thank you for verifying this. I will close; official 2.12.0 will take a while to be released unfortunately.

**Comment by blackdigger1337** [comment]
Hi, it seems the snapshot has stopped working for me...

Originally I've used defaults from spring boot, which resolved to 2.11.0.
And in order to use your fix, I've added
```
implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.12.0-SNAPSHOT")
implementation("com.fasterxml.jackson.core:jackson-databind:2.12.0-SNAPSHOT")
implementation("com.fasterxml.jackson.core:jackson-core:2.12.0-SNAPSHOT")
```

It was working for a couple of weeks, but it seems that at some point the snapshot has changed and dependency version combination above has stopped working and I get runtime error event if I rebuild previous versions of my app:
```
NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonIncludeProperties$Value
```
So I've added extra line which I thought should fix the issue:
```
implementation("com.fasterxml.jackson.core:jackson-annotations:2.12.0-SNAPSHOT")
```
But the error is now the following:
```
java.lang.AbstractMethodError
```
Probably I'm missing something else, but can't figure it out.
I've looked at the list of my project dependencies, its quite complex including various spring boot starters so I've just updated all jackson-related modules to the snapshot version, the list is here:
```
com.fasterxml.jackson.core:jackson-annotations:2.12.0-SNAPSHOT
com.fasterxml.jackson.core:jackson-core:2.12.0-SNAPSHOT
com.fasterxml.jackson.core:jackson-databind:2.12.0-SNAPSHOT
com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.12.0-SNAPSHOT
com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.12.0-SNAPSHOT
com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.0-SNAPSHOT
com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.12.0-SNAPSHOT
com.fasterxml.jackson.module:jackson-module-kotlin:2.11.0
com.fasterxml.jackson.module:jackson-module-parameter-names:2.12.0-SNAPSHOT
com.fasterxml.woodstox:woodstox-core:6.2.1
com.fasterxml:classmate:1.5.1
```
The only dependency I was unable to find snapshot is jackson-module-kotlin - so it is main suspect.
Another ideas is that classmate should also be updated, but I don't know which version to use.
Which jackson components should I upgrade to new snapshot version?

BTW is there any rough estimate when 2.12 gets released?

**Comment by cowtowncoder** [comment]
@blackdigger1337 Snapshot builds are likely to break temporarily every now and then, unfortunately, due to various reasons, both due to timing (of when Travis builds and publishes new versions after commits), and due to problems with CI/CD itself (annotations auto-publish was not working for some reason.
So you may use snapshots for testing but they cannot be relied on for anything much more, that is the nature of these builds unfortunately. You may be able to to pin specific snapshots that you find usable (full version, including timestamp), at most.

As to release, I am hoping that release would get done by September 2020. Work being done, planned, can be found on:

https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress

but of everything that could be done, there are maybe 3 issues I really want to get included (JDK 14 record support; DB#2715 (class-loading issue); DB#1498 (single-arg creators).
After those, release candidate(s) shuld be released (maybe towards end of August).

**Comment by blackdigger1337** [comment]
@cowtowncoder Thanks for reply!
Yeah, I realize that snapshots are unstable.
I guess, at this point I'm just trying to understand if my configuration is right...
Maybe I was just lucky that I didn't run into such problem when I've used a mixture of 2.11.0 and 2.12-SNAPSHOT and now my luck has run out when some cross-dependencies happened :)
I just hoped there may be some known issue which you have already came across and my attempts to fix things are futile...

**Comment by blackdigger1337** [comment]
Ok, it seems the problem is gone now, I don't know if you have changed anything or some caches were invalidated...
In any case, thanks for the help.

**Comment by cowtowncoder** [comment]
I know what the specific problem was: I merged PRs to add support for `@JsonIncludeProperties`, but `jackson-annotations` snapshot was not being published by Travis CI for some reason, but `jackson-databind` was (or I forced databind to be deployed locally, where I had locally built annotations snapshot). Either way, there was discrepancy so that snapshots were not in sync.

I will do my best to keep snapshots working, of course, breakages are not intentional.
Going forward you can file an issue if you observe a problem that lasts for longer than couple of hours, the only thing I ask is patience with possible transient problems. It may take a while for me to notice, due to combination of local builds, remote publish.

**Comment by blackdigger1337** [comment]
@cowtowncoder Thanks again for quick fix :) Keep up great job you do with jackson!

**Comment by cowtowncoder** [comment]
Thank you!
